[package]
name = "otio-sys"
version = "0.1.0"
edition = "2021"
description = "FFI bindings to the OpenTimelineIO C-Bindings library"
license = "MIT"
build = "build.rs"

[build-dependencies]
cmake = "0.1"
bindgen = "0.71"

[features]
otio-native = []

[dependencies]
